#!/usr/bin/env node

args		= require('./rename/args');
utils		= require('./libs/utils');

// Input arguments
var inputKeyOldName = program.old;
var inputKeyNewName = program.new;

console.assert( inputKeyNewName );
console.assert( inputKeyOldName );

utils.readJSONFromSTDIN( function( tweet ) {

	tweet[ inputKeyNewName ] = tweet[ inputKeyOldName ];
	delete tweet[ inputKeyOldName ];

	process.stdout.write( JSON.stringify( tweet ) + "\n" )
} );
