#!/usr/bin/env node

program = require('commander');

program
	.version('0.0.1')
	.command('fake [options]', 'create a fake tweet; useful for debugging')
	.command('fetch [options]', 'fetch tweets from Twitter or database')
	.command('filter [options]', 'filters twitter according to an user-defined predicate')
	.command('rename [options]', 'renames a field from a json object' )
	.command('save [options]', 'save data to a database')
	.command('search [options]', 'search a database with tweets')
	.command('sentiment [options]', 'tweet sentiment analysis')
	.command('summary [options]', 'summarize input data')
	.parse(process.argv);

if( process.argv.length <= 2 ) {
	program.help();
}