#!/usr/bin/env node

program = require('commander');

program
	.version('0.0.1')
	.command('add [options]', 'add app keys to a local database')
	.command('list', 'list the keys stored into the local database')
	.parse(process.argv);

if( process.argv.length <= 2 ) {
	program.help();
}