#!/usr/bin/env node

var mkdirp      = require( "mkdirp" );
var Twit        = require( "twit" );
var    _        = require( "underscore" );
var fs 		      = require( "fs" );
var MongoClient = require('mongodb').MongoClient;

var args   = require( "./database/credentials/add/args" );
var utils  = require( "./libs/utils" );

var inputMongoURL = program.mongourl;

process.stderr.write( "\n" );
process.stderr.write( "* chom-database-credebtuaks-add" + "\n" );
process.stderr.write( "  * parameters settings:\n" );
process.stderr.write( "    * mongo-url   : " + JSON.stringify( inputMongoURL ) + "\n" );
process.stderr.write("\n");

//
// Testing whether those credentials are valid
//
MongoClient.connect( inputMongoURL, function( err, db ) {

	if( err )  {
		process.stdout.write( '* Could not add database:' + inputMongoURL );
		process.stdout.write( '* \tError:' + JSON.stringify( err ) );
		
		db.close();
		throw err;
	}

		//
		// Credentials are ok. Let's save them
		//
		saveCredentials( inputMongoURL, db );

	} 
);

function getUserHome() {
  return process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'];
}

//
// Save credentials to disk
//
var chomDir = utils.getCHOMDir();
function saveCredentials( credentials, db ) {
	mkdirp( chomDir, function(err) { 

		if( err ) {
			db.close();
			throw err;
		}

		var credentialsFile = chomDir + "/mongourl-credentials.json";
		if ( !fs.existsSync( credentialsFile ) ) {
			fs.writeFileSync( credentialsFile, "{}" );
		}

		var credentialsMap = JSON.parse( fs.readFileSync( credentialsFile ) );
		var next = _.keys( credentialsMap ).length;
		credentialsMap[ next ] = credentials;
		fs.writeFileSync( credentialsFile, JSON.stringify( credentialsMap ) );

		db.close();
	} );
}