#!/usr/bin/env node

program = require('commander');

program
	.version( '0.0.1' )
	.command( 'insert [options]', 'insert a new json object to the database' )
	.parse( process.argv );

if( process.argv.length <= 2 ) {
	program.help();
}
