#!/usr/bin/env node

_ = require("underscore");
MongoClient = require('mongodb').MongoClient;
ObjectID = require('mongodb').ObjectID,

args = require('./save/args');
utils = require('./libs/utils');

// Input arguments
var inputDatabase = program.database;
var inputKeys = program.keys;
var inputCode = ( program.code ) ? Function( "datum", program.code ) : undefined;
var inputMaxBufferSize = program.max;
var inputCastField = _.filter( program.cast, function( value, idx ) { return idx % 2 == 0; } ) ;
var inputCastType = _.filter( program.cast, function( value, idx ) { return idx % 2 == 1; } ) ;
var inputSaveInterval = program["save-interval"];
var inputInsert = program.insert;

if( _.isEmpty( program.collection ) != true ) {
	inputDatabase.collection = program.collection;
}

if( !inputDatabase ) {
	process.stderr.write( "  * Missing database information\n" );
	program.help();
}

if( !inputKeys ) {
	inputKeys = [];
	process.stderr.write( "  * Missing keys to be used. Trying \"_id\"\n" );

	inputKeys.push( "_id" );
	inputCastField.push( "_id" );
	inputCastType.push( "objectid" );
}

var database;
var queue = {};
var timestamp = [];

MongoClient.connect( inputDatabase.mongo_url, function( err, db ) {

	if( err )  {
		console.log( '* Error found while connecting to the database:', err );
		throw err;
	}
	database = db;

	var collection = database.collection( inputDatabase.collection );

	//
	//
	//
	var isSaving = false;
	setInterval( function() { 

		//
		// If we are in the process of saving data to the database,
		// let's to start saving more data and overloaded the
		// server in the process
		//
		if( isSaving == true )
			return;


		//
		// Ok, we will start a potentially expensive operation
		// Setting isSaving to true will lock the network communication
		// for the current data in queue
		//
		isSaving = true;

		//
		// MongoDB bullk operation. We don't care about the order
		// in which the data is save.
		//
		var bulkOperations = collection.initializeUnorderedBulkOp();

		//
		// Counting operation. We do not want to call .execute()
		// if we do not have to
		//
		var operationCounter = 0;

		//
		// For each element in queue, let's schedule
		// an operation
		//
		_.each( queue, function( value, key ) {

			if( value.modified ) {

				var datum = _.extend( {}, value )
				delete datum[ "modified" ];

				if( inputInsert ) {
					bulkOperations.insert( datum );
				} else {

					//  If we wish to update the date, then
					// we must build a query based on keys
					var query = { };
					_.each( inputKeys, function( key ) {
						query[ key ] = datum[ key ];
						delete datum[ key ];
					} );

					bulkOperations.find( query ).upsert().updateOne( { $set : datum } );	
				}
				operationCounter++;
			}
		} );

		if( operationCounter == 0 ) {

			// 
			// If no operation was scheduled, let's continue
			//
			isSaving = false;

		} else {

			//
			// Marking everything as modified
			// 
			_.each( queue, function( value, key ) { value.modified = false; } );

			//
			// Let's try to save the data, if for some reason it doesn't succeed,
			// then print the error
			//
			try {
				var timeout = 5000000;

				bulkOperations.execute( { w: 1, wtimeout : timeout }, function( err, ret ) {
					if( err ) 
						console.log( "* error: ", err );
					
					isSaving = false;
				} );

			} catch ( err ) {

				console.log( "* exception ", err );
				
				//
				// If a error accurs, we discard whatever was in the queue 
				// up until this point, restart bulk operations, and set 
				// isRunning to false
				// 
				isSaving = false;
			}
		}
	}, inputSaveInterval );
});

function getKey( datum ) {
	var key = "";
	_.each( inputKeys, function( k, idx ) { 
		key += JSON.stringify( datum[ k ] ); 
		if( idx < inputKeys.length-1 )
			key += ",";
	} );
	return key;
}


function cast( datum ) {

	_.each( inputCastField, function( field, idx ) {
		if( _.isEqual( inputCastType[ idx ].toLowerCase(), "date" ) == true ) {
			datum[ field ] = new Date( datum[ field ] );
		} else if( _.isEqual( inputCastType[ idx ].toLowerCase(), "objectid" ) ) {
			datum[ field ] = new ObjectID( datum[ field ] )
		} else {
			console.assert( 0 && "no such type" );
		}
	} );

}

function runCode( datum ) {

	if( inputCode ) {
		inputCode( datum );
	}

}

utils.readJSONFromSTDIN( function( datum ) {

	if( _.isEmpty( datum ) ) {

		process.stderr.write( "* Closing db " );
		database.close();
		process.exit();
		return;

	}

	//
	// If user wants to cast some field to
	// some type, then this will happen here 
	//
	cast( datum );

	//
	//  If user wants to run custom code,
	//  then, it will happen here
	//
	runCode( datum );


	// Keeping the queue to a maximum size
	// in order to avoid explosion memory use
	if( inputMaxBufferSize != 0 && _.size( queue ) >= inputMaxBufferSize ) {
		delete queue[ timestamp.shift() ];
	}
	

	// Extracting key and value from data
	var key = getKey( datum );
	
	if( _.has( queue, key ) ) {
		datum.modified = queue[ key ].modified;
	}	

	// If new data is different from old data, 
	// then update it
	if( _.isEqual( queue[ key ], datum ) == false ) {
		datum.modified = true;
		queue[ key ] = datum;

		if( inputMaxBufferSize != 0 ) {
			// Saving the order in which data is inserted
			// Old data gets removed if inputMaxBufferSize
			// is reached
			timestamp.push( key );	
		}
	}

} );
