#!/usr/bin/env node

var utils = require( "./libs/utils" );
var args = require( "./summary/args" );
var TimeTree = require( "./libs/timetree" );

var _ = require( "underscore" );

var totalNumberOfTweets = { };
var AccountsTree = {};

var inputField = program.field;
var inputDepth = program.depth;

process.stderr.write("\n");
process.stderr.write( "* chom-summary" + "\n");
process.stderr.write( "  * parameters settings:" + "\n");
process.stderr.write( "    * field: " + JSON.stringify( inputField ) + "\n" );
process.stderr.write( "    * depth: " + inputDepth + "\n" );
process.stderr.write("\n");

if( !inputField ) {
	process.stderr.write( "\n  * Missing field information\n" );
	program.help();
}

if( !inputDepth ) {
	process.stderr.write( "\n  * Missing max key depth \n" );
	program.help();	
}

utils.readJSONFromSTDIN( function( tweet ) {
	
	if( _.isEmpty( tweet ) ) {
		setTimeout( function() {
			process.stdout.write( JSON.stringify( {} ) + "\n" );	
			process.stderr.write("* chom-summary close\n");
			process.exit();	
		}, 5000);
		return;
	}


	var twitter_handle = tweet.keyword;

	if( _.has( AccountsTree, twitter_handle ) == false ) {

		AccountsTree[ twitter_handle ] = TimeTree.TimeTree();

		AccountsTree[ twitter_handle ]
			.depth( inputDepth )
			.dateValuer( function( d ) { return new Date( d.created_at ); } )
			.valuer( function( d ) { 
				if( isNaN( d[ inputField ] ) || d[ inputField ] === null ) {
			  		return 0;
			  	}
			  	return parseFloat( d[ inputField ] ); 
			}).build();

			totalNumberOfTweets[ twitter_handle ] = 0;
	}

	totalNumberOfTweets[ twitter_handle ] += 1;
	AccountsTree[ twitter_handle ].add( tweet );

} );

setInterval( function() {
	summarize();
}, 1000 );

function summarize( ) {

	_.each( AccountsTree, function( timetree, twitter_handle ) {

		for(var idx = 0; idx < timetree.depth(); ++idx) {

			var data = [];
			var interval = timetree.interval( idx );

			_.each( timetree.get( idx ), function( d ) {

				var datum = { 
					date : d.date, 
					counter : d.counter, 
					updated : d.updated,
				};
				datum[ inputField ] = d.field;
				data.push( datum );

			});

			data = _.sortBy( data, 'date');

			if(data.length === 0)
				continue;

			_.each( data, function( datum ) {

				if( datum.updated === true ) {

					timetree.updated( idx,  +datum.date, false );

					var out = { 
						twitter_handle : twitter_handle, 
						depth : idx, 
						date : +datum.date, 
						counter : datum.counter, 
					}
					out[ inputField ] = datum[ inputField ];

					process.stdout.write( JSON.stringify( out ) + "\n" );
				}
			});
		}
	} );
}

utils.printToFile( "/tmp/chom.summary.txt", totalNumberOfTweets );