#!/usr/bin/env node

_ = require("underscore");
args = require('./extract/args');
utils = require('./libs/utils');

var inputField = program.field;

var list = [];

utils.readJSONFromSTDIN( function( datum ) {

	if( _.isEmpty( datum ) ) {
		process.stdout.write( JSON.stringify( list ) );
		process.exit();
		return;
	}

	list.push( datum[ inputField ] );
} );