#!/usr/bin/env node

_ = require('underscore')
args		= require('./rename/args');
utils		= require('./libs/utils');

// Input arguments
var inputKeyOldName = program.old;
var inputKeyNewName = program.new;

console.assert( inputKeyOldName );

var noNewName = _.isEmpty( inputKeyNewName );

utils.readJSONFromSTDIN( function( tweet ) {

	if( noNewName == false )
		tweet[ inputKeyNewName ] = tweet[ inputKeyOldName ];

	delete tweet[ inputKeyOldName ];

	process.stdout.write( JSON.stringify( tweet ) + "\n" )
} );
