#!/usr/bin/env node

Sentiment 		= require('sentiment');

args			= require('./sentiment/args');
utils			= require('./libs/utils');

var _ = require( "underscore" );

process.stderr.write("\n");
process.stderr.write( "* chom-sentiment" + "\n");
process.stderr.write("\n");

function sentiment( text ) {
	var sentiment =  Sentiment( text ).comparative;
	return ( _.isNumber( sentiment ) ) ? sentiment : 0;
}

utils.readJSONFromSTDIN( function( tweet ) {
	
	if( _.isEmpty( tweet ) ) {
		process.stdout.write( JSON.stringify( {} ) + "\n" );	
		process.stderr.write("* chom-sentiment close\n");
		process.exit();	
	}

	tweet.sentiment = sentiment( tweet.text );

	// Saving to database
	process.stdout.write( JSON.stringify( tweet ) + "\n" );
} );