#!/usr/bin/env node

program = require('commander');

program
	.version('0.0.1')
	.command('add [options]', 'add mongoDB info to local database')
	.command('list', 'list the stored mongoDBs')
	.parse(process.argv);

if( process.argv.length <= 2 ) {
	program.help();
}