#!/usr/bin/env node

var mkdirp = require( "mkdirp" );
var fs 		 = require( "fs" );
var _ 		 = require( "underscore" );
var utils  = require('./libs/utils');


process.stderr.write( "\n" );
process.stderr.write( "* chom-database-credentials-list\n");
process.stderr.write("\n");


function getUserHome() {
  return process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'];
}

//
// List credentials already stored on disk
//
var chomDir = utils.getCHOMDir();
mkdirp( chomDir, function(err) { 

	if( err ) {
		throw err;
	}

	var credentialsFile = chomDir + "/mongourl-credentials.json";

	if ( !fs.existsSync( credentialsFile ) ) {
		fs.writeFileSync( credentialsFile, "{}" );
	}

	var credentialsMap = JSON.parse( fs.readFileSync( credentialsFile ) );
	console.log( credentialsMap );
} );