#!/usr/bin/env node
_ 				= require("underscore");
MongoClient	= require('mongodb').MongoClient;

args			= require('./libs/args');
out				= require('./libs/out');
utils			= require('./libs/utils');


// Input arguments
var inputDatabase = params.database;

var totalNumberOfTweets = {};
var database;
MongoClient.connect( inputDatabase.mongo_url, function(err, db) {
	if(err)  {
		console.log('* Error found while connecting to the database:', err);
		throw err;
	}
	database = db;
	var collection = database.collection( inputDatabase.collection );
	out.callback( function( data ) { 
		collection.save(data, function(err) {
			if(err) {
				console.log('* Error found while inserting data into the database:', err);
				throw err;
			}
		});
	} );
});

utils.readJSONFromSTDIN( function( tweet ) {

	if( _.isEmpty( tweet ) ) {
		console.log( "* Closing db " );
		database.close();
		process.exit();
		return;
	}

	// Saving to database
	out.print( tweet );

	// Updating the tweet count
	if( _.has( totalNumberOfTweets, tweet.keyword ) == true ) {
		totalNumberOfTweets[ tweet.keyword ] += 1;
	}
	else {
		totalNumberOfTweets[ tweet.keyword ] = 1;
	}
} );

// Peridiocally outputs the number of tweets saved 
utils.printToFile( "/tmp/chom.save.txt", totalNumberOfTweets );